### ISSUE TITLE
leaf name is not compiling into [Function: _Class] correctly

### ISSUE THREAD

**Issue by javadoug** [stormstack/yang-compiler#1]
@saintkepha my goal is to render a YANG schema into a JSON representation for use as an aid in rendering configuration options in a UI. I'm not sure of the best way to do this but I found your YANG compiler has helped me toward my goal. I managed to create a script that generates a JSON document that provides the basic schema data that I want. However, it seems a config leaf property named `name` is lost for some reason. Is this a bug?

Here is a sample schema that generates a compiled configuration that does not contain name as expected.

```
module test {

  container test {

    leaf id {
      description "Identifier for the test.";
      type string;
    }

    leaf name {
      description "Name of test.";
      type string;
    }

  }

}
```

In javascript, do the following:

```
var fs = require('fs');
var YangCompiler = require('yang-compiler');
var schema = fs.readFileSync('./test.yang', {encoding: 'utf-8'});

var Test = YangCompiler.compile(schema);
console.log(Test.test.name); // _Class
console.log(Test.test.name.type); // undefined
console.log(Test.test.name.description); // undefined
console.log(Test.test.id);// { [Function: _Class] ...}
console.log(Test.test.id.type);// string
console.log(Test.test.id.description);// Identifier for the test.

Actual Console Output:
WARN: compiler does not have sub-statement declared for revision
WARN: compiler does not have sub-statement declared for yang-version
_Class
undefined
undefined
{ [Function: _Class] ... removed for readability}
string
Identifier for the test.
```

**Comment by saintkepha** [comment]
Hi Doug, the yang-compiler project has been superseded by http://github.com/saintkepha/yangforge. 

Please give that a look and see if that helps better address your goals. 

Thanks,

Peter Lee

**Comment by javadoug** [comment]
Thanks for the tip, Peter. I'll give that a try.
